  
# ---------- Extra installables -----------------------------------------------
# example of path from different sources:
#   [git] danu: "git+ssh://git.link/danu@master"
#   [remote] efas: "cade:/home/mo/mojp/src/efas"
#   [local] glofas: "/home/mo/mojp/projects/glofas_comfies"
packages:
  meteokit: 
    source: git+ssh://git.ecmwf.int/ecsdk/meteokit.git@master
    installer: /home/macw/git/pproc/pproc-ci/installers/meteokit.sh
  mir_python: 
    source: git+ssh://git.ecmwf.int/mir/mir-python.git@master
    installer: /home/macw/git/pproc/pproc-ci/installers/mir_python.sh
  pyfdb: 
    source: git+ssh://git.ecmwf.int/mars/pyfdb.git@develop
    installer: /home/macw/git/pproc/pproc-ci/installers/pyfdb.sh
  eccodeshl: 
    source: /home/macw/git/pproc/eccodeshl
    installer: /home/macw/git/pproc/pproc-ci/installers/eccodeshl.sh
  ppop: 
    source: /home/macw/git/pproc/ppop
    installer: /home/macw/git/pproc/pproc-ci/installers/ppop.sh

# --------Virtual envs --------------------------------------------------
# conda or venv virtual environments
# example of virtual environemnts:
# System environments: (depends on module and packages above)
#   myenv1: 
#        type: system_venv
#        depends = [python3, gdal]
#        packages: [danu, efas]
# Pure virtual environments (conda and venv): (standalone)
#   myenv2:
#        type: venv
#        file: /path/to/env/file
#        packages: python==3.6, pcraster==4.3.0
#        depends = [danu, efas]
#   myenv3:
#        type: conda
#        environment: env_name #(or path)
#   myenv4:
#        type: conda
#        file: /path/to/env/file
#        depends = [danu, efas]
#   myenv5:
#        type: conda
#        packages: 'python==3.6 pcraster==4.3.0'
#        depends = [danu, efas]
environments:
    pproc_env:
        type: conda
        file: /home/macw/git/pproc/pproc-ci/config/atos/environment.yaml
        packages: [meteokit, mir_python, pyfdb, eccodeshl, ppop]

# ---------- Data paths-------- -----------------------------------------------
# example of path:
#   - local link: "path/to/dir"
#   - ecfs archive: "ec:/path/to/archive.tgz"
#   - remote copy: "remote:path/to/dir"
#   - git: git+ssh://git.ecmwf.int/cefl/danu.git@develop
#   - MARS ?
static_data:
  fdb_templates: /home/macw/git/pproc/pproc-ci/fdb_templates
