# ---------- System modules ---------------------------------------------------
# Examples:
#  python3:
#    name: python3
#    version: 3.6.10-01
modules:
  python3:
    version: '3.8.8-01'
  cmake:
    version: '3.19.5'
  fftw:
    version: '3.3.4.11'
  
# ---------- Extra installables -----------------------------------------------
# example of path from different sources:
#   [git] danu: "git+ssh://git.link/danu@master"
#   [remote] efas: "cade:/home/mo/mojp/src/efas"
#   [local] glofas: "/home/mo/mojp/projects/glofas_comfies"
packages:
  meteokit: 
    source: git+ssh://git.ecmwf.int/ecsdk/meteokit.git@master
  pproc_bundle: 
    source: ravenglass:/home/ma/macw/git/pproc/pproc-bundle
    depends: ['cmake', 'fftw']
  mir_python: 
    source: git+ssh://git.ecmwf.int/mir/mir-python.git@master
    depends: ['pproc_bundle']
  pyfdb: 
    source: git+ssh://git.ecmwf.int/mars/pyfdb.git@develop
    depends: ['pproc_bundle']
  eccodeshl: 
    source: ravenglass:/home/ma/macw/git/pproc/eccodeshl
  ppop: 
    source: ravenglass:/home/ma/macw/git/pproc/ppop

# --------Virtual envs --------------------------------------------------
# conda or venv virtual environments
# example of virtual environemnts:
# System environments: (depends on module and packages above)
#   myenv1: 
#        type: system_venv
#        depends = [python3, gdal]
#        packages: [danu, efas]
# Pure virtual environments (conda and venv): (standalone)
#   myenv2:
#        type: venv
#        file: /path/to/env/file
#        packages: python==3.6, pcraster==4.3.0
#        depends = [danu, efas]
#   myenv3:
#        type: conda
#        environment: env_name #(or path)
#   myenv4:
#        type: conda
#        file: /path/to/env/file
#        depends = [danu, efas]
#   myenv5:
#        type: conda
#        packages: 'python==3.6 pcraster==4.3.0'
#        depends = [danu, efas]
environments:
    pproc_env:
        type: system_venv
        depends: [python3]
        packages: [meteokit, pproc_bundle, mir_python, pyfdb, eccodeshl, ppop]


# ---------- Data paths-------- -----------------------------------------------
# example of path:
#   - local link: "path/to/dir"
#   - ecfs archive: "ec:/path/to/archive.tgz"
#   - remote copy: "remote:path/to/dir"
#   - git: git+ssh://git.ecmwf.int/cefl/danu.git@develop
#   - MARS ?
static_data:
  fdb_templates: ravenglass:/home/ma/macw/git/pproc/suite/fdb_templates