#!/usr/bin/env bash

# BOOTSTRAP ecbundle-build, and pass arguments to it

BOOTSTRAPPED=ecbundle-build
BUNDLE_DIR="$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd -P )"

# Download ecbundle scripts if not already available
command_exists () { type "$1" &> /dev/null ; }
if ! command_exists ${BOOTSTRAPPED} ; then
    if [[ ! -d ${BUNDLE_DIR}/ecbundle ]]; then
        if [[ -z "${BITBUCKET}" ]]; then
          BITBUCKET=ssh://git@git.ecmwf.int
        fi
        git clone ${BITBUCKET}/ecsdk/ecbundle.git ${BUNDLE_DIR}/ecbundle
    fi
    export PATH=${BUNDLE_DIR}/ecbundle/bin:${PATH}
fi

# Make sure python has version 2.7
python_version_ok=$(python -c "import sys; print( sys.version_info[:3] >= tuple(map(int, '2.7'.split('.'))))")
if [[ "${python_version_ok}" != "True" ]]; then
    if [[ ${ARCH:-unset} == "cray" ]]; then
        { module unload python; module load python; } 2>/dev/null
    else
        echo "ERROR: Installed python requires version \"2.7\" or greater"
        exit 1
    fi
fi

${BOOTSTRAPPED} "$@"
