name: cd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # NOTE there are other tags for generating "unstable modules", those should *not* trigger pypi upload

jobs:

  pypi:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    secrets: inherit
