name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ruff
      - run: ruff check
  ppruntime_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v7
    - name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run checks and tests
      run: |
        cd pproc-runtime
        export UV_FROZEN=1
        export SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0
        uv sync --prerelease allow --python "${{ matrix.python_version }}" --all-packages
        uv run --prerelease allow prek --directory . --config ../.pre-commit-config.yaml
        uv run --prerelease allow ty check
        if [ -d "tests" ]; then
          uv run --prerelease allow -m pytest tests/ -v
        fi

  ppcore_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v7
    - name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run checks and tests
      run: |
        cd pproc-core
        export UV_FROZEN=1
        uv sync --python "${{ matrix.python_version }}" --all-packages
        uv run prek --directory . --config ../.pre-commit-config.yaml
        if [ -d "tests" ]; then
          uv run -m pytest tests/ -v
        fi

  pproc_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run pproc tests
      run: |
        cd pproc
        export UV_FROZEN=1
        uv sync --python "${{ matrix.python_version }}" --all-packages
        uv run prek --directory . --config ../.pre-commit-config.yaml
        if [ -d "tests" ]; then
          uv run --prerelease allow -m tests/ -v
        fi
